services:
  node:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
      - '5173:5173'
      - '6006:6006'
    tty: true
  app:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    tty: true
  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/db:/var/lib/mysql
