services:
  node:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
      - '5173:5173'
      - '6006:6006'
    tty: true
  app:
    build: ./backend
    volumes:
      - ./backend/app:/app
    ports:
      - "8080:8080"
    tty: true
