name: Lint

on:
  pull_request:
    branches: [ main, develop, 'feature/**', 'hotfix/**' ]
  push:
    branches: [ main, develop, 'feature/**', 'hotfix/**' ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.17.0'
    
    - uses: pnpm/action-setup@v4
      with:
        version: 9
        run_install: false
    
    - name: Install dependencies
      run: pnpm install
      working-directory: frontend
    
    - name: Run ESLint
      run: pnpm run lint
      working-directory: frontend